openshift/ci-docs

- content/docs/getting-started/_index.md
- content/docs/getting-started/examples.md
- content/docs/getting-started/useful-links.md
- content/docs/how-tos/testing-operator-sdk-operators.md
Ref https://issues.redhat.com/browse/DPTP-1620
Copies the remaining content from the step registries help:
* https://steps.ci.openshift.org/help/operators
* https://steps.ci.openshift.org/help/examples
* https://steps.ci.openshift.org/help/links
> Port remaining docs from the step registry

- content/en/docs/architecture/step-registry.md
Implementation: https://github.com/openshift/ci-tools/pull/1311.
> Document `readonly_shared_dir`

- content/en/docs/architecture/ci-operator.md
- content/en/docs/getting-started/examples.md
- content/en/docs/how-tos/external-images.md
Ref: https://issues.redhat.com/browse/DPTP-1638
> Document How to Integrate External Images For Tests

- content/en/docs/how-tos/onboarding-a-new-component.md
Follow up https://coreos.slack.com/archives/GB7NB0CUC/p1604091493327800?thread_ts=1604091482.327700&cid=GB7NB0CUC
/cc @stevekuznetsov @alvaroaleman
> Document openshift-merge-robot's write permission

- content/en/docs/how-tos/migrating-template-jobs-to-multistage.md
> Migrating tempalte jobs to multi-stage

- content/en/docs/how-tos/migrating-template-jobs-to-multistage.md
/cc @stevekuznetsov @alvaroaleman
> Template migration: document user-facing differences

- content/en/docs/architecture/branch-protection.md
Fixes: [DPTP-1673](https://issues.redhat.com/browse/DPTP-1673)
> Document the branch protect:false quirks

- config.yaml
> Add link to the ci-operator reference

- content/en/docs/how-tos/mirroring-to-quay.md
This is a frequent gotcha, so few words about it may preempt one or two #forum pings
> mirroring: warn about new images being private by default

- content/en/docs/how-tos/onboarding-a-new-component.md
> onboard: fix broken links

- content/en/docs/how-tos/use-registries-in-build-farm.md
https://issues.redhat.com/browse/DPTP-1613
> Document Registry Logins and Unauthenticated Errors

- content/en/docs/how-tos/adding-a-new-secret-to-ci.md
https://issues.redhat.com/browse/DPTP-1674
> Document adding a new secret to CI

- content/en/docs/how-tos/use-registries-in-build-farm.md
/assign @bparees @alvaroaleman
> registry: update docs

- content/en/docs/how-tos/use-registries-in-build-farm.md
> remove petr's name

- content/en/docs/how-tos/use-registries-in-build-farm.md
> apply link styling to registry URLs

- content/en/docs/how-tos/use-registries-in-build-farm.md
> Use registry: Reference pre-defined role that also allows pulling

- content/en/docs/how-tos/mirroring-to-quay.md
Catch up with https://github.com/openshift/release/pull/14590
/cc @alvaroaleman
> Use registry-access folder in image-mirroring doc

- content/en/docs/how-tos/onboarding-a-new-component.md
- content/en/docs/how-tos/use-registries-in-build-farm.md
"next section" is ambiguous, let's be more specific and also use a link.
> Onboard: clarification

- content/en/docs/how-tos/notification.md
Follow up https://coreos.slack.com/archives/CBN38N3MW/p1609943344119500?thread_ts=1609942509.111700&cid=CBN38N3MW
> How to set up slack notifications for a job

- content/en/docs/how-tos/adding-a-new-secret-to-ci.md
> How to use a secret in a job

- content/en/docs/how-tos/use-registries-in-build-farm.md
/assign @petr-muller @alvaroaleman
> registries: be more explicit in directions

- content/en/docs/how-tos/adding-a-new-secret-to-ci.md
/assign @hongkailiu @petr-muller
> docs: improve doc on secret management

- content/en/docs/architecture/timeouts.md
https://issues.redhat.com/browse/DPTP-1631
> Document Timeouts

- content/en/docs/architecture/quota-and-leases.md
- content/en/docs/architecture/step-registry.md
Fixes a couple broken links in CI docs.
> Fixes broken links

- content/en/docs/architecture/ci-operator.md
> ci-operator: doc both promotion types

- content/en/docs/how-tos/use-registries-in-build-farm.md
> images: doc RBAC for pullers

- content/en/docs/architecture/ci-operator.md
> fix a typo that's been driving me crazy

- content/en/docs/architecture/step-registry.md
> Remove dead link to template parameters

- content/en/docs/how-tos/adding-a-new-secret-to-ci.md
> secrets: fix a link

- Dockerfile.links
Required by https://github.com/openshift/release/pull/15467
> Add Dockerfile.links

- Dockerfile.links
Fix https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/15467/rehearse-15467-pull-ci-openshift-ci-docs-master-links/1356976394319433728#1:build-log.txt%3A33
> links image: install bash

- content/en/docs/architecture/quota-and-leases.md
- content/en/docs/architecture/release-gating.md
- content/en/docs/architecture/step-registry.md
- content/en/docs/how-tos/migrating-template-jobs-to-multistage.md
- content/en/docs/how-tos/onboarding-a-new-component.md
- content/en/docs/how-tos/testing-operator-sdk-operators.md
- content/en/docs/how-tos/use-registries-in-build-farm.md
https://issues.redhat.com/browse/DPTP-1901
> Fix the broken links

- content/en/docs/architecture/step-registry.md
> ci-operator: update docs on provided env

- content/en/docs/architecture/images.md
https://issues.redhat.com/browse/DPTP-1851
> Document images built by CI and ART

- content/en/docs/architecture/step-registry.md
/cc @stevekuznetsov @alvaroaleman
> Fix a broken link on registry page

- content/en/docs/how-tos/testing-operator-sdk-operators.md
> docs: fix tag name

- content/en/docs/architecture/ci-operator.md
> ci-operator: clarify tag_specification release names

- content/en/docs/how-tos/interact-with-running-jobs.md
1) how to interact with running ci job
2) don't interact with running ci job, run `openshift-tests` binary yourself
> add how-to interact with ci job & openshift-tests

- content/en/docs/architecture/step-registry.md
https://github.com/openshift/ci-tools/pull/1657
Also slightly improves the existing description of chain/workflow/test
field propagation.
> step-registry: document new resolution rules

- content/en/docs/architecture/step-registry.md
> oc injection: describe releases

- content/en/docs/how-tos/interact-with-running-jobs.md
I did:
- standardized some language
- made notes format nicely
- added a nice script for kubeconfig (what's a better way to do this ... ?)
- fixed line-end lengths
/assign @sallyom
> debugging jobs: copy-edits

- content/en/docs/architecture/timeouts.md
/assign @bbguimaraes @petr-muller @alvaroaleman
> docs: document timeouts with more specifics

- content/en/docs/architecture/release-gating.md
- content/en/docs/architecture/step-registry.md
- content/en/docs/how-tos/add-jobs-to-testgrid.md
- content/en/docs/how-tos/adding-a-new-secret-to-ci.md
- content/en/docs/how-tos/onboarding-a-new-component.md
- content/en/docs/how-tos/use-registries-in-build-farm.md
> docs: use actual alerts instead of bold text

- content/en/docs/architecture/timeouts.md
Follows up on https://github.com/openshift/ci-tools/pull/1717
Part of [DPTP-1668](https://issues.redhat.com/browse/DPTP-1668)
> ci-operator: update timeout doc for new fields

- content/en/docs/architecture/branching.md
Implements [DPTP-1904](https://issues.redhat.com/browse/DPTP-1904)
/assign @petr-muller @AlexNPavel 
I have a couple ideas for how to improve this doc but for now let's just get it committed.
> branching: add basic FAQ from Google Doc

- content/en/docs/architecture/branching.md
ports https://docs.google.com/document/d/12J89AQdEAanvBIzD4OS4eq1F5iR_UIOfg9yDqWkQpNU/edit#
> branching: add phases tables

- content/en/docs/how-tos/migrating-template-jobs-to-multistage.md
Resolves: [DPTP-1848](https://issues.redhat.com/browse/DPTP-1848)
My goal was to write a doc that I coujld link to from an email to aos-devel saying "Please migrate handcrafted jobs on your repositories", but after trying, I'm not convinced that the doc is actually that useful: the decision space is simply too large to be conveniently described :(
> Document how to migrate handcrafted template jobs to generated

- config.yaml
- content/en/docs/architecture/branch-protection.md
- content/en/docs/architecture/ci-operator.md
- content/en/docs/architecture/images.md
- content/en/docs/architecture/private-repositories.md
- content/en/docs/architecture/quota-and-leases.md
- content/en/docs/architecture/release-gating.md
- content/en/docs/architecture/step-registry.md
- content/en/docs/architecture/timeouts.md
- content/en/docs/getting-started/examples.md
- content/en/docs/getting-started/useful-links.md
- content/en/docs/how-tos/add-jobs-to-testgrid.md
- content/en/docs/how-tos/adding-a-new-secret-to-ci.md
- content/en/docs/how-tos/adding-changing-step-registry-content.md
- content/en/docs/how-tos/contributing-openshift-release.md
- content/en/docs/how-tos/external-images.md
- content/en/docs/how-tos/interact-with-running-jobs.md
- content/en/docs/how-tos/migrating-template-jobs-to-multistage.md
- content/en/docs/how-tos/mirroring-to-quay.md
- content/en/docs/how-tos/notification.md
- content/en/docs/how-tos/onboarding-a-new-component.md
- content/en/docs/how-tos/testing-operator-sdk-operators.md
- content/en/docs/how-tos/use-registries-in-build-farm.md
make things nicer by default, stop cargo-culting random things
> hugo cleanup

- netlify.toml
> Update hugo version used in preview to 0.80.0

- config.yaml
- content/en/docs/_index.md
- layouts/shortcodes/card.html
Ref https://issues.redhat.com/browse/DPTP-1681
> Add a landing page

- content/en/docs/architecture/ci-operator.md
Docs [DPTP-2051](https://issues.redhat.com/browse/DPTP-2051)
/assign @petr-muller @droslean
> ci-operator: document build cache

- content/en/docs/architecture/bugzilla.md
Ref https://issues.redhat.com/browse/DPTP-1764
/assign @bparees @cuppett 
You were mentioned as the ideal condidates to review this :)  You will find a preview of this below when clicking on the `Details` of the `netlify/preview` status.
Is there any additional documentation that should be linked from here?
> Document bugzilla integration

- content/en/docs/how-tos/testing-operator-sdk-operators.md
This PR adds documentation on creating tests for optional operator
upgrades, fixes a mistake in the simple operator installation example,
and changes the name of the operator in the example to a generic example
name.
/cc @petr-muller @stevekuznetsov
> testing-operator-sdk-operators: add update docs

- content/en/docs/how-tos/external-images.md
/assign @openshift/openshift-team-developer-productivity-test-platform
> images: doc reference policy for private images

- content/en/docs/architecture/ci-operator.md
- content/en/docs/how-tos/cluster-claim.md
https://issues.redhat.com/browse/DPTP-2100
> Document how to claim a cluster for a job

- content/en/docs/architecture/step-registry.md
/assign @openshift/openshift-team-developer-productivity-test-platform
> steps: clarify $SHARED_DIR

- content/en/docs/architecture/step-registry.md
Follow up https://github.com/openshift/ci-docs/pull/123#discussion_r621571527
/cc @petr-muller
> IMAGE_FORMAT is not set in case of claiming a cluster

- content/en/docs/architecture/ci-operator.md
https://issues.redhat.com/browse/DPTP-2157
> Doc build_args of ci-op's config

- content/en/docs/architecture/step-registry.md
- content/en/docs/how-tos/adding-a-new-secret-to-ci.md
Ref https://issues.redhat.com/browse/DPTP-2068
/hold
until this is actually live
> Document Vault user secrets

- content/en/docs/how-tos/adding-a-new-secret-to-ci.md
Requires to https://github.com/openshift/ci-tools/pull/1975 to not be a lie
/hold
Ref https://issues.redhat.com/browse/DPTP-2172
> Secretsync: Document targeting a cluster subset

- content/en/docs/architecture/ci-operator.md
- content/en/docs/getting-started/useful-links.md
- content/en/docs/how-tos/cluster-claim.md
https://issues.redhat.com/browse/DPTP-2187
> Update the hive cluster in the doc

- content/en/docs/architecture/ci-operator.md
Follow up https://github.com/openshift/ci-tools/pull/2019
https://issues.redhat.com/browse/DPTP-2157
https://bugzilla.redhat.com/show_bug.cgi?id=1956826
> buildArgs: No value from a secret

- content/en/docs/how-tos/external-images.md
https://issues.redhat.com/browse/DPTP-2257
/cc @stevekuznetsov @petr-muller
/hold
wait for https://github.com/openshift/release/pull/18979
> Mirror ci images instead of importing

- config.yaml
- content/en/docs/architecture/ci-operator.md
- content/en/docs/how-tos/cluster-claim.md
- layouts/partials/head-css.html
- layouts/partials/head.html
- layouts/shortcodes/rawhtml.html
https://issues.redhat.com/browse/DPTP-2242
/hold
wait for the deployment of https://github.com/openshift/ci-tools/pull/2075
> List cluster pools on the hive cluster

- content/en/docs/architecture/ci-operator.md
- content/en/docs/how-tos/cluster-claim.md
This PR concludes https://issues.redhat.com/browse/DPTP-2335
> Explain the discovered pools

- content/en/docs/architecture/ci-operator.md
Adds documentation for feature in https://github.com/openshift/ci-tools/pull/2074.
> architecture: update cluster claim docs

- content/en/docs/how-tos/cluster-claim.md
> Populate the secrets for Hive only to cluster hive

- content/en/docs/architecture/ci-operator.md
Follow up https://coreos.slack.com/archives/CBN38N3MW/p1624989481278300?thread_ts=1624982977.263800&cid=CBN38N3MW
/cc @petr-muller
> Access the pull secret in a test with a claim

- content/en/docs/architecture/ci-operator.md
- content/en/docs/how-tos/cluster-claim.md
Also, add a paragraph about when it is suitable to use which pool.
> pools: rename 'dpp' owner to 'openshift-ci'

- content/en/docs/architecture/ci-operator.md
- content/en/docs/getting-started/examples.md
Ref https://issues.redhat.com/browse/DPTP-2263
> Document container test clone setting

- content/en/docs/how-tos/cluster-claim.md
We went through these steps with @ironcladlou, and hope this can benefit the pool owners in the future.
/cc @petr-muller
> Document how to access the Hive's installation logs

- content/en/docs/how-tos/mirroring-to-quay.md
/assign @openshift/test-platform
> mirroring: update secret comments

- content/en/docs/how-tos/adding-a-cluster-profile.md
> how-tos: add a doc on cluster profiles

- content/en/docs/architecture/ci-operator.md
I was confused about a couple of things regarding image `promotion:` while reading the docs. Add words for future-me.
> Clarify promotion

- content/en/docs/how-tos/cluster-claim.md
Update docs for new functionality from https://github.com/openshift/ci-tools/pull/2206.
/cc @stevekuznetsov
> cluster-claim: add version bound labels to docs

- content/en/docs/architecture/ci-operator.md
- content/en/docs/how-tos/contributing-openshift-release.md
> add docs for the run_if_changed/skip_if_only_changed/optional fields

- content/en/docs/architecture/branching.md
> branching: document no-FF and fix staff-eng label

- content/en/docs/how-tos/cluster-claim.md
/cc @2uasimojo @samvarankashyap
> cluster pools: rotate cloud credentials

- content/en/docs/how-tos/interact-with-running-jobs.md
> PR author accessing testing ns: support SSO KID

- content/en/docs/architecture/step-registry.md
> Add info on the shm-size option

- content/en/docs/how-tos/adding-a-new-secret-to-ci.md
I _think_ this makes the requirement clearer.
> Clarify the secretsync KV requirements

- content/en/docs/getting-started/useful-links.md
- content/en/docs/how-tos/use-registries-in-build-farm.md
- layouts/partials/head.html
https://issues.redhat.com/browse/DPTP-2635
/hold
require https://github.com/openshift/release/pull/24421
> Generate clusters dynamically

- content/en/docs/getting-started/useful-links.md
> Clarify the login method to CI clusters

- content/en/docs/architecture/ci-operator.md
/cc @alvaroaleman @AlexNPavel @openshift/test-platform
> Explain release name in a test using cluster claim

- content/en/docs/how-tos/cluster-claim.md
- content/en/docs/how-tos/interact-with-running-jobs.md
- content/en/docs/how-tos/rbac.md
- content/en/docs/how-tos/use-registries-in-build-farm.md
/hold
Requires https://github.com/openshift/release/pull/25357/files
> Set Up RBACs on CI Clusters

- content/en/docs/how-tos/cluster-claim.md
/cc @2uasimojo @openshift/test-platform
> clusterpool: hibernationConfig.resumeTimeout

- content/en/docs/how-tos/use-registries-in-build-farm.md
> Link to the RBAC page

- content/en/docs/getting-started/useful-links.md
- content/en/docs/how-tos/interact-with-running-jobs.md
https://issues.redhat.com/browse/DPTP-2659
> Announce RH SSO is the only IDP

- content/en/docs/architecture/branch-protection.md
The feature is brought by a recent PR.
https://github.com/kubernetes/test-infra/pull/25456
> Lower levels can override `unmanaged: true`

- content/en/docs/architecture/ci-operator-internals/_index.md
- content/en/docs/architecture/ci-operator-internals/steps.md
I'm planning to extend this document in different ways in the future,
make it a proper section since it's already large enough for one page.
---
Opening as work-in-progress because I'm not sure if/how these things work in
Hugo.
> ci-operator: create internals section

- content/en/docs/how-tos/adding-a-new-secret-to-ci.md
> Secretsync: Document multi-ns targeting feature

- content/en/docs/how-tos/adding-a-cluster-profile.md
Resolves: [DPTP-2727](https://issues.redhat.com/browse/DPTP-2727)
> Link to Provider Onboarding Guide from cluster profile doc

- content/en/docs/how-tos/use-registries-in-build-farm.md
> Update how to login on clusters in the registry doc

- content/en/docs/architecture/retester.md
Initial version of the retester documentation page.
[DPTP-2827](https://issues.redhat.com/browse/DPTP-2827)
> retester: Added retester page

- content/en/docs/architecture/step-registry.md
- content/en/docs/how-tos/adding-a-cluster-profile.md
https://deploy-preview-249--zealous-shirley-0f56b3.netlify.app/docs/architecture/step-registry/#vpn-connection
https://deploy-preview-249--zealous-shirley-0f56b3.netlify.app/docs/how-tos/adding-a-cluster-profile/#vpn-connection
> step-registry: document VPN support

- .gitignore
- content/en/docs/architecture/_index.md
- content/en/docs/getting-started/_index.md
- content/en/docs/getting-started/examples.md
- content/en/docs/getting-started/useful-links.md
- content/en/docs/how-tos/_index.md
- content/en/docs/release-oversight/_index.md
Signed-off-by: ehila <ehila@redhat.com>
> feat: reorder side menu to easily find getting started

- content/en/docs/release-oversight/troubleshooting-payload-failures.md
Starter for outlining tools and strategies for troubleshooting payload failures
> trt-240: starter troubleshooting doc

- Dockerfile
- Dockerfile.links
- config.yaml
- netlify.toml
Updated the [docsy](https://github.com/google/docsy) submodule to latest.
Desired New Features:
- More `shortcodes` to help present information
- Texonomy support for better tagging of content
Signed-off-by: ehila <ehila@redhat.com>
> feat: updated theme submodule to latest

- OWNERS
> OWNERS file reconciliation

- content/en/docs/how-tos/interact-with-running-jobs.md
Regarding [TRT-245](https://issues.redhat.com/projects/TRT/issues/TRT-245)
View the [rendered pages produced by CI](https://deploy-preview-265--zealous-shirley-0f56b3.netlify.app/docs/how-tos/interact-with-running-jobs/#how-to-run-test-suites-using-cluster-bot-development-cluster) so you can see what the changes will look like when merged.
TODO: retry the different combinations given that I figured out the `--provider` options and have a gcp credentials file (and can extract one from the cluster-bot cluster):
> Add section on running openshift-tests for test suites

- content/en/docs/release-oversight/improving-ci-signal.md
- content/en/docs/release-oversight/testing-in-production.md
This is based on discussions today between Test Platform and the TRT.
> Adding documentation to describe sprint upgrades

- content/en/docs/release-oversight/payload-testing.md
https://issues.redhat.com/browse/DPTP-2643
> Doc new payload commands

- content/en/docs/getting-started/useful-links.md
It will help to let our users know about the slack workflows.
> Describe the slack workflows and when to use them

- content/en/docs/how-tos/interact-with-running-jobs.md
> DPTP-2978: update github link info

- content/en/docs/how-tos/artifacts.md
https://deploy-preview-266--zealous-shirley-0f56b3.netlify.app/docs/how-tos/artifacts/
> how-tos: document artifacts directory

- content/en/docs/release-oversight/disruption-testing/job-primer.md
Signed-off-by: ehila <ehila@redhat.com>
> doc: update information on when job primer runs

- content/en/docs/architecture/step-registry.md
https://github.com/openshift/ci-tools/pull/2930
https://issues.redhat.com/browse/DPTP-3038
/cc @ncdc 
/assign @smg247
> document how to turn off the SA/kubeconfig

- content/en/docs/how-tos/pr-reminder.md
https://github.com/openshift/ci-docs/issues/280
> fix typo in doc

- content/en/docs/architecture/retester.md
Added config file overview and made few changes in `How Do We Set up Retester?`
[ci-tools PR](https://github.com/openshift/ci-tools/pull/2868)
[DPTP-2828](https://issues.redhat.com/browse/DPTP-2828)
> retester: Added config file

- content/en/docs/architecture/retester.md
The old retester has been removed in: https://github.com/openshift/release/pull/31861
> Remove references to the old retester

- content/en/docs/architecture/ci-operator-internals/_index.md
For: https://issues.redhat.com/browse/DPTP-3114
> Note the change to cleanupDuration

- content/en/docs/how-tos/contributing-openshift-release.md
https://deploy-preview-299--zealous-shirley-0f56b3.netlify.app/docs/how-tos/contributing-openshift-release/#tolerated-changes-to-generated-jobs
> how-tos: update list of tolerated fields

- content/en/docs/how-tos/adding-a-new-secret-to-ci.md
Having gone through the process and used the helpful docs a few hours ago, this was fresh in my mind.  I added a few more details to enhance clarity.
> Enhance the doc on adding self-serve secrets for jobs in CI

- content/en/docs/how-tos/cluster-claim.md
- layouts/partials/head.html
/hold
wait for https://github.com/openshift/ci-tools/pull/3129
> cluster pools: add #standby for pools

- content/en/docs/how-tos/mirroring-to-quay.md
Learned it from forum.
https://coreos.slack.com/archives/CBN38N3MW/p1668088117762529?thread_ts=1667895440.604169&cid=CBN38N3MW
Might be useful to others.
> Mirror images with wildcard

- content/en/docs/how-tos/contributing-openshift-release.md
/cc @droslean @openshift/test-platform
> Specify that `pj-rehearse` reacts to PR body description and comments

- content/en/docs/architecture/step-registry.md
Pod-scaler does that: increase and decrease (not commonly known).
> The resources of a pod might be overwritten

- content/en/docs/how-tos/contributing-openshift-release.md
/cc @droslean @openshift/test-platform
> Add info about rehearsing specific jobs

- content/en/docs/architecture/quota-and-leases.md
https://issues.redhat.com/browse/DPTP-3251
> fix grafana link

- content/en/docs/architecture/ci-operator.md
> Fix testing ephemeral cluster ci-operator config example

- content/en/docs/architecture/ci-operator-internals/artifacts.md
/hold
Requires https://github.com/openshift/ci-docs/pull/319 for cross-references.
> ci-operator-internals: document artifact gathering

- content/en/docs/how-tos/testing-operator-sdk-operators.md
https://issues.redhat.com/browse/DPTP-2969
/cc @openshift/test-platform @joelanford @grokspawn
> Moving to File-Based Catalog

- content/en/docs/release-oversight/disruption-testing/data-architecture.md
/assign @dgoodwin 
Signed-off-by: ehila <ehila@redhat.com>
> upkeep: added explicit cluster link for upkeep job location

- content/en/docs/how-tos/external-images.md
To follow up https://github.com/openshift/release/pull/35899#issuecomment-1412900678
/cc @smg247 @paigerube14
> Ensure the target namepsace to exist for image mirroring

- content/en/docs/getting-started/useful-links.md
For: https://issues.redhat.com/browse/DPTP-2937
> Link to Google Chat backup spaces

- content/en/docs/getting-started/useful-links.md
Petr's was linked twice, I found Bruno's and updated the link.
> Correct link for Bruno's ci-operator presentation recording

- content/en/docs/how-tos/testing-operator-sdk-operators.md
> oo-testing: fix a format issue

- content/en/docs/how-tos/testing-operator-sdk-operators.md
Require https://github.com/openshift/ci-tools/pull/3327
/hold
> oo-testing: opt out building index image

- content/en/docs/release-oversight/payload-testing.md
For: https://issues.redhat.com/browse/DPTP-3322
> add info about aborting payload jobs

- content/en/docs/how-tos/testing-operator-sdk-operators.md
Follow up https://redhat-internal.slack.com/archives/CBN38N3MW/p1686482315713579
Thanks to @nunnatsa and his team, we have the alternative workflows to do OO-testing.
/cc @nunnatsa @openshift/test-platform
> Document step/optional-operators-ci-operator-sdk-$CLOUD

- content/en/docs/how-tos/testing-operator-sdk-operators.md
https://issues.redhat.com/browse/DPTP-3506
@fedepaol @openshift/test-platform
> oo-testing: clarify $OO_BUNDLE_INIT

- content/en/docs/how-tos/contributing-openshift-release.md
Updates incorrect (old) wording.
/cc smg247
> Update rehearsal docs

- content/en/docs/architecture/ci-operator.md
Add a warning to Test with Clusters from HyperShift section to emphasis this is a pilot program with limited supports.
> Add warning to HyperShift

- content/en/docs/getting-started/useful-links.md
For: https://issues.redhat.com/browse/DPTP-3568
/hold until channel rename occurs
> Update forum channel name

- content/en/docs/release-oversight/disruption-testing/code-implementation.md
- content/en/docs/release-oversight/disruption-testing/data-architecture.md
- content/en/docs/release-oversight/risk-analysis.md
- content/en/docs/release-oversight/troubleshooting-payload-failures.md
Adds an overview of Risk Analysis and a small update for search.ci metrics.
> trt-1125: document risk analysis

- content/en/docs/architecture/release-gating.md
[TRT-1187](https://issues.redhat.com//browse/TRT-1187)
> Clarify TRT reverts and shortcuts to jobs going release blocking

- content/en/docs/architecture/jira.md
> jira: include new features to the documentation

- content/en/docs/how-tos/testing-operator-sdk-operators.md
> operator-sdk: add catalog build ci-chat-bot command

- content/en/docs/release-oversight/improving-ci-signal.md
> It's Mr Fisher, Ronald Fisher

- content/en/docs/how-tos/testing-operator-sdk-operators.md
/cc @openshift/test-platform @razo7
> Clarify the usage of optional-operators-ci-operator-sdk-$CLOUD workflows

- content/en/docs/release-oversight/risk-analysis.md
[TRT-1167](https://issues.redhat.com/browse/TRT-1167)
> Update to consecutive failures for commenting

- OWNERS
> Add psalajova to owners

- content/en/docs/how-tos/adding-a-cluster-profile.md
Adding information to the docs about how to make a cluster profile private.
> Add private cluster profiles section

- content/en/docs/release-oversight/payload-testing.md
For: https://issues.redhat.com/browse/DPTP-3685
> add info about manually submitting `PRPQR` spec with multiple PRs provided

- content/en/docs/release-oversight/payload-testing.md
TRT would like to see the full CR documented so they can easily apply these
> add info about manually submitting PRPQR spec

- content/en/docs/how-tos/adding-a-new-secret-to-ci.md
Preview: https://deploy-preview-411--zealous-shirley-0f56b3.netlify.app/docs/how-tos/adding-a-new-secret-to-ci/
> Clarify adding a secret instructions

- content/en/docs/how-tos/use-registries-in-build-farm.md
- layouts/partials/head.html
https://issues.redhat.com/browse/DPTP-3749
/cc @openshift/test-platform @jupierce
> The image registry on app.ci is deprecated

- content/en/docs/how-tos/use-registries-in-build-farm.md
> Fix some typos

- content/en/docs/architecture/ci-operator.md
- layouts/partials/head.html
/assign @bear-redhat 
/hold
Require https://github.com/openshift/ci-tools/pull/3813
> Generate Hypershift's supported versions

- content/en/docs/architecture/ci-operator.md
> Add a note about Hypershift's supported versions

- content/en/docs/how-tos/use-registries-in-build-farm.md
> fix the vsphere image registry URL link

- content/en/docs/getting-started/examples.md
- content/en/docs/how-tos/mirroring-to-quay.md
- content/en/docs/how-tos/onboarding-a-new-component.md
Give folks some heads up on these review processes, so they are less likely to dive into implementation and then be surprised by approvers wanting changes to their early choices.
> content/en/docs/how-tos/onboarding-a-new-component: Enhancement and image-naming

- content/en/docs/how-tos/contributing-openshift-release.md
This [functionality](https://github.com/openshift/ci-tools/blob/e7438f6b96627667aa4e4e17751f6e25d065fcf3/pkg/prowgen/prowgen.go#L76-L79) has existed for awhile now, but the docs are out of date.
> Correct options for postsubmits

- content/en/docs/release-oversight/payload-testing.md
A couple of new commands have been added to the `payload-testing-prow-plugin`.
> Detail new payload commands

- content/en/docs/architecture/ci-operator.md
https://issues.redhat.com/browse/DPTP-3845
/cc @openshift/test-platform @bparees
/hold
Requiring https://github.com/openshift/ci-tools/pull/3918
> Run a presubmit for a periodic

- content/en/docs/how-tos/adding-a-new-secret-to-ci.md
Follow up https://redhat-internal.slack.com/archives/CBN38N3MW/p1706875012741849 
Provide suggestions before https://issues.redhat.com/browse/DPTP-3855 is implemented.
> Best practice on secret names

- content/en/docs/release-oversight/payload-testing.md
For: https://issues.redhat.com/browse/DPTP-3687
> Document ability to override payload pull-specs

- content/en/docs/release-oversight/payload-testing.md
For: https://issues.redhat.com/browse/DPTP-3688
> `payload-testing`: override specific image tags

- Dockerfile
- Dockerfile.links
Errors previously looked like: [failure](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_ci-docs/431/pull-ci-openshift-ci-docs-master-links/1757736155958218752)
> update builder images to attempt to fix bug with building

- content/en/docs/release-oversight/payload-testing.md
Specify how to achieve this, and add a warning about limitations.
For: https://issues.redhat.com/browse/DPTP-3686
/cc @danilo-gemoli
> `payload-testing`: Add details for submitting PRPQR without PR info

- netlify.toml
An attempt to fix the failing `deploy/netlify` test, maybe related to the changes here https://github.com/openshift/ci-docs/pull/432
> Update hugo version in netlify.toml

- OWNERS
Add @Prucek & remove bbguimaraes from/to OWNERS.
> owners: add Prucek & remove bruno

- layouts/partials/head.html
We should do the same for the content as well.
But this is more urgent in javascript.
> Update the name of the hive cluster: hosted-mgmt

- content/en/docs/architecture/private-repositories.md
- content/en/docs/how-tos/notification.md
- content/en/docs/how-tos/onboarding-a-new-component.md
- content/en/docs/internals/artifacts.md
- content/en/docs/internals/configuration-updates.md
- content/en/docs/internals/steps.md
- content/en/docs/internals/timeouts.md
> Update links for prow repository

- content/en/docs/internals/images-in-ci.md
> How to troubleshoot CI image issues

- content/en/docs/internals/images-in-ci.md
> How to troubleshoot CI image issues (revise)

- content/en/docs/how-tos/cluster-claim.md
> Fixing the docs for host-mgmt cluster pools

- content/en/docs/how-tos/cluster-claim.md
/cc @bear-redhat @openshift/test-platform
> Updating references for Hive with Hosted-mgmt

- content/en/docs/architecture/ci-operator.md
> Fix a link for hive

- content/en/docs/how-tos/adding-a-cluster-profile.md
For: https://issues.redhat.com/browse/DPTP-3929
> `BYOIP`: document usage

- content/en/docs/how-tos/use-registries-in-build-farm.md
> qci-appci: clarify a RBAC setup

- config.yaml
- content/en/docs/getting-started/helpdesk-faq.md
- layouts/partials/head.html
This will serve as the frontend for the `helpdesk-faq`. It is a simple table that reuses existing logic to display all of the items in a searchable, expandable format.
For: [DPTP-3521](https://issues.redhat.com/browse/DPTP-3521)
/hold merge after https://github.com/openshift/ci-tools/pull/4048
> `helpdesk-faq`: basic page with table display

- content/en/docs/how-tos/use-registries-in-build-farm.md
> Update QCI docs for login and pulling images

- content/en/docs/how-tos/adding-a-new-secret-to-ci.md
> DPTP-4031: Updating docs for aggressive censoring

- content/en/docs/how-tos/cluster-claim.md
> Update the default networkType for cluster pools install config

- content/en/docs/how-tos/notification.md
For https://issues.redhat.com/browse/DPTP-3366 and https://issues.redhat.com/browse/DPTP-2875
> add information about the slack_reporter config within prowgen

- content/en/docs/internals/images-in-ci.md
A small change. I was reading the docs and thought the original sentence was a bit confusing, so this is an attempt to make its meaning more clear.
/cc @hongkailiu @deepsm007
> Reword a sentence about IST resolution

- OWNERS
Added hector-vido to OWNERS file.
> Added hector-vido to OWNERS

- content/en/docs/how-tos/cluster-claim.md
[HIVE-2598](https://issues.redhat.com//browse/HIVE-2598)
> Link Hive ClusterPool troubleshooting doc

- content/en/docs/architecture/ci-operator.md
> note about `restrict_network_access` rehearsals, and remove `build10`

- content/en/docs/architecture/ci-operator.md
For: https://issues.redhat.com/browse/DPTP-4171
> Update to reference the limited rehearsal support for 'restrict_network_access'

- content/en/docs/architecture/ci-operator.md
For: https://issues.redhat.com/browse/DPTP-4195
> Specify new rehearsal workflow for INTRANET tests

- content/en/docs/how-tos/multi-pr-presubmit-testing.md
For: https://issues.redhat.com/browse/DPTP-4148
> document the `multi-pr-prow-plugin`

- content/en/docs/how-tos/multi-pr-presubmit-testing.md
> `multi-pr`: fix omission

- content/en/docs/how-tos/adding-a-cluster-profile.md
Updates the docs with the new way of handling secrets.
/hold
> Update cluster profile secret section

- content/en/docs/how-tos/adding-a-cluster-profile.md
For https://issues.redhat.com/browse/DPTP-4113
To be merged after https://github.com/openshift/ci-tools/pull/4391
/hold
> Remove ConfigMap sections

- OWNERS
Add @pruan-rht and @liangxia to OWNERS
> owners: add pruan-rht and liangxia

- content/en/docs/how-tos/multi-architecture.md
> [DPTP-4292] initialize the multi-arch related configuration for image builds and tests

- content/en/docs/how-tos/multi-architecture.md
follow-up of https://github.com/openshift/ci-docs/pull/517
> multi-arch: include information about the default architecture and behavior on image builds

- content/en/docs/how-tos/capabilities.md
> Update docs with existing capabilities

- content/en/docs/release-oversight/pull-request-testing.md
For: https://issues.redhat.com/browse/DPTP-4278
> `payload-testing`: update steps to override a specific image tag

- content/en/docs/how-tos/onboarding-a-new-component.md
for reference: https://redhat-internal.slack.com/archives/CBN38N3MW/p1744746643018129
> update outdated mojo link to source.redhat.com

- content/en/docs/internals/images-in-ci.md
```
- ./public/docs/internals/images-in-ci/index.html
*  External link https://docs.openshift.com/container-platform/4.15/openshift_images/image-configuration.html#images-configuration-registry-mirror_image-configuration failed: got a time out (response code 301)
```
> Fix links check

- content/en/docs/how-tos/adding-a-cluster-profile.md
> Update docs for AWS quota and pruner

- .gitignore
> Revert "Add .DS_store files to gitignore"

- content/en/docs/architecture/timeouts.md
timeout in the configs, https://github.com/openshift/release/blob/71e8b75500cd0da5dde94a64c246f0b638c4dfd3/core-services/prow/02_config/_config.yaml#L458-L460
> Sync timeout in configs and docs
