openshift/ci-docs

content/docs/architecture/step-registry.md

This implements DPTP-1242
xref https://github.com/openshift/ci-tools/pull/1296

ci-operator: document CLI injection

---

config.yaml

Based on [these docs][1].
[1]: https://github.com/google/docsy/blob/4808e0ac5bb2df27021401fd33b2ef2756f751c2/userguide/content/en/docs/Adding%20content/repository-links.md#github_repo

config: Set github_repo to link the source

---

content/docs/how-tos/mirroring-to-quay.md

Largely a copy of https://github.com/openshift/release/blob/08b11329d589e0ee26208bc1f36a1076c3c3a75f/core-services/image-mirroring/README.md#L1 but without the outdated list of existing mirroring target.
Ref https://issues.redhat.com/browse/DPTP-1548

Add Mirror an image to an external registry doc

---

content/docs/architecture/quota-and-leases.md

Catching up with openshift/release@5cf5ba3f87 (openshift/release#11752).

content/docs/architecture/quota-and-leases: Doc generate-boskos.py

---

content/docs/how-tos/onboarding-a-new-component.md

This PR adds the onboarding document https://docs.google.com/document/d/1SQ_qlkcplqhe8h6ONXdgBr7YUVbs4oRSj4ISl3gpLW4/edit?ts=5e4f0618# with some minor adjustments:
* Mention the step registry rather than templates for e2e tests
* Don't tell ppl to execute commands to view promoted images
* Link to https://github.com/openshift/ci-docs/pull/7 for branch protection
* Link to https://github.com/openshift/ci-docs/pull/9 for mirroring to an external registry
Ref: https://issues.redhat.com/browse/DPTP-1571

Add onboarding document

---

content/en/docs/architecture/ci-operator.md
content/en/docs/architecture/step-registry.md
content/en/docs/how-tos/onboarding-a-new-component.md

To match the downcased, hyphenated anchors that the docs actually use.

content/docs: Fix '#Configuring Inputs' and other references

---

content/en/docs/architecture/ci-operator.md

Typo from a93b6be28c (#4).
/assign @alvaroaleman

content/en/docs/architecture/ci-operator: Fix '.ci-operator.yaml' quoting

---

content/en/docs/architecture/step-registry.md

In order for the users to be able to inject their custom credentials in their job, they need first to have their secret mapped in the test-crendentials namespace. 

[DPTP-1699] update the Injecting Custom Credentials documentation

---

content/en/docs/architecture/private-repositories.md
content/en/docs/how-tos/contributing-openshift-release.md
content/en/docs/how-tos/testing-operator-sdk-operators.md

Backticks are fine for display-style in plain text, but we don't want them in link targets.  This fixes typos introduced in 0423b9b402 (#4) and subsequent commits.

content/en/docs/*: Fix ci-operator and index target quoting

---

content/en/docs/how-tos/testing-operator-sdk-operators.md

These were originally from 7563b0c65c (#5), but we don't need code-styling backticks within the YAML block.

content/en/docs/how-tos/testing-operator-sdk-operators: Fix backticks in YAML

---

content/en/docs/architecture/ci-operator.md
content/en/docs/getting-started/examples.md

We've had over-quoting on these entries since a93b6be28c (#4).

content/en/docs: Reduce excessive `bin` and `src` backticks

---

Dockerfile
nginx/relative_redirect.sh

Before:
```
$ curl --silent --show-error --head https://docs.ci.openshift.org/docs \
>     | grep --ignore-case location:
location: http://docs.ci.openshift.org:8080/docs/
```
After:
```
$ curl --silent --show-error --head localhost:8000/docs \
>     | grep --ignore-case location:
Location: /docs/
```

nginx: use relative redirects

---

content/en/docs/architecture/step-registry.md

The linter is not happy when I fail to indent the multiline string started with `|-`

Fix multiline comment syntax for Description

---

content/en/docs/how-tos/external-images.md

Follow up
https://github.com/openshift/release/pull/14498

Use the supplemental-ci-images folder on app.ci

---

content/en/docs/how-tos/mirroring-to-quay.md

- Modification on `roles.yaml` is no longer needed because we do oc-image-mirror to promote with the push-token from a SA which can push images to all namespaces on `app.ci`.
- For image-mirroring jobs, the RBAC and the namespace should be in `app.ci` folder (I have moved the existing ones while moving the jobs) since they are running there now.
/cc @stevekuznetsov @alvaroaleman

Update image-mirroring doc

---

content/en/docs/architecture/step-registry.md

Fix `allow_best_effort_post_steps` ident in `Marking `post` Steps Best-Effort` example.
Fixes up #42

step-registry.md: fix identation

---

content/en/docs/how-tos/use-registries-in-build-farm.md

without the prefix, clicking the registry hyperlinks takes
you to a 404. example:
https://docs.ci.openshift.org/docs/how-tos/use-registries-in-build-farm/registry.ci.openshift.org
not that browsing to the https:// registry link does anything
more than give a blank page, but that's better than a 404.
Signed-off-by: Jamo Luhrsen <jluhrsen@gmail.com>

Add https:// to registry links

---

README.md
content/en/docs/architecture/branch-protection.md
content/en/docs/architecture/ci-operator.md
content/en/docs/architecture/private-repositories.md
content/en/docs/architecture/quota-and-leases.md
content/en/docs/architecture/release-gating.md
content/en/docs/architecture/step-registry.md
content/en/docs/architecture/timeouts.md
content/en/docs/getting-started/examples.md
content/en/docs/getting-started/useful-links.md
content/en/docs/how-tos/add-jobs-to-testgrid.md
content/en/docs/how-tos/adding-a-new-secret-to-ci.md
content/en/docs/how-tos/adding-changing-step-registry-content.md
content/en/docs/how-tos/contributing-openshift-release.md
content/en/docs/how-tos/external-images.md
content/en/docs/how-tos/migrating-template-jobs-to-multistage.md
content/en/docs/how-tos/mirroring-to-quay.md
content/en/docs/how-tos/notification.md
content/en/docs/how-tos/onboarding-a-new-component.md
content/en/docs/how-tos/testing-operator-sdk-operators.md
content/en/docs/how-tos/use-registries-in-build-farm.md

We currently get the default behavior which is to embed the entire first
paragraph into the OpenGraph tag, which leads to Slack previews showing
massive walls of text when unfurling a link.
/assign @alvaroaleman @petr-muller

all: add description field for OpenGraph tags

---

config.yaml

Asked https://discourse.gohugo.io/t/how-to-use-relative-urls/31052
It seems that the problem is caused by the theme.
But their example website has no such issues.
https://example.docsy.dev/docs/getting-started/example-page/
Its config is
https://github.com/google/docsy-example/blob/f96057c72dbc519c24b9d232a71109869200a047/config.toml#L1
Rehearsed with
https://github.com/openshift/ci-docs/pull/83
It works.
/cc @alvaroaleman @stevekuznetsov

Remove hostname in the base url

---

content/en/docs/how-tos/migrating-template-jobs-to-multistage.md

The link is fixed https://github.com/openshift/ci-docs/pull/81/files#diff-26dee95e4ddfaaf0560727186a3503f453730feecb75ebe90f4e06729aab2445R144
The reason the link was broken is that the loki version becomes the default and the loki is removed in the name of the workflow.
https://github.com/openshift/release/pull/14217
We correct the name here.
/cc @alvaroaleman

Fix a workflow name

---

content/en/docs/how-tos/adding-a-new-secret-to-ci.md
content/en/docs/how-tos/use-registries-in-build-farm.md

OpenShift will not be happy with users that try to look for their own
projects/namespaces or use `oc project` if they do not have at least
this permission in those namespaces. While the previous roles are
technically the minimal set, this additional role does not give them any
privileges that are worrisome and will allow the CLI to operate clearly.
/assign @alvaroaleman 
/cc @ray-harris

various: add view role to admins

---

content/en/docs/getting-started/examples.md

Remove the code block brackets from the `cluster_profile` inside of the
"Adding a Reusable Test Step" example documentation.

Remove code block brackets inside of reusable test step example

---

content/en/docs/architecture/step-registry.md

Follows up on https://github.com/openshift/ci-tools/pull/1718
Part of [DPTP-1668](https://issues.redhat.com/browse/DPTP-1668)

ci-operator: always use secret wrapper

---

content/en/docs/architecture/timeouts.md

"both" made sense before e70c36d37a (#102), but should have been dropped when that commit shifted artifact-uploading outside of the configured `grace_period`.

content/en/docs/architecture/timeouts: Fix "to both generate" typos

---

content/en/docs/how-tos/testing-operator-sdk-operators.md

This PR adds documentation for the new ci-operator features being added
in https://github.com/openshift/ci-tools/pull/1748.

content/en/docs/how-tos/testing-operator...: add named bundle docs

---

content/en/docs/architecture/ci-operator.md
content/en/docs/how-tos/contributing-openshift-release.md
content/en/docs/how-tos/use-registries-in-build-farm.md

Makes the links job fail: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ci-docs/114/pull-ci-openshift-ci-docs-master-links/1374744159927144448

Remove references to api.ci registry

---

content/en/docs/how-tos/use-registries-in-build-farm.md

Almost everyone wanting to run through this path will want
to pull a release image using the pull spec from the release page.
Let's document how to log into the new `app.ci` cluster which
is the backend for that registry.  (This linkage isn't immediately
obvious)

docs/registries: Document logging into app.ci, not build01

---

content/en/docs/how-tos/use-registries-in-build-farm.md

- officially announce in our doc that registry on `api.ci` is gone. Replace its references.
- (not directly related to api.ci) explain benefit of image replacement in ci-operator's config.

Announce that registry on api.ci is offline

---

content/en/docs/how-tos/testing-operator-sdk-operators.md

From a93b6be28c (#4), `pipeline` is for:
> Input images described with base_images and build_root as well as images holding built artifacts (such as src or bin) and output images as defined in images.
while `stable` is for:
> ..., but for the release:latest release payload. Appropriate tags are overridden using the container images built during the test.
In this example, `operand` is coming from `base_images`, and is not being built for this job, so we want to use `pipeline:operand` to get at it.

content/en/docs/how-tos/testing-operator-sdk-operators: "stable" -> "pipeline"

---

content/en/docs/architecture/branching.md

I think that @eparis 's [comment](https://github.com/openshift/ci-docs/pull/108#discussion_r589492228) was [interpreted](https://github.com/openshift/ci-docs/pull/108#issuecomment-792882984) incorrectly. We never needed approvals on `master`.
/cc @jupierce @stevekuznetsov

branching: master/main does not require cherry-pick-approved in feature freeze

---

content/en/docs/architecture/ci-operator.md

Expanding on the descriptions from a93b6be28c (#4).  I didn't understand:
* Whether this was contacting [the official Red Hat Cincinnati](https://api.openshift.com/api/upgrades_info/v1/graph) or [the release-controller Cincinnati](https://amd64.ocp.releases.ci.openshift.org/graph).  It's the former.
* The fact that `channel` has the major.minor suffix added instead of being passed through directly to Cincinnati.
* The fact that the `version` is not (yet, openshift/ci-tools#1927) allowed to include a full semantic version.  Instead, it's currently only used to append to `channel`, and the selected version is the largest SemVer entry in that channel.
[1]: https://github.com/openshift/ci-tools/pull/1927

content/en/docs/architecture/ci-operator: More details for release channel/version

---

content/en/docs/architecture/ci-operator.md

Catching up with openshift/ci-tools#1927.  We'd flubbed 4.4.2 and earlier, so 4.4.3 ended up being the name of the first GA 4.4 release:
```console
$ curl -sH accept:application/json 'https://api.openshift.com/api/upgrades_info/v1/graph?channel=stable-4.4' | jq -r '.nodes[] | .version + " " + .payload' | grep '^4[.]4[.]' | sort -V | head -n2
4.4.3 quay.io/openshift-release-dev/ocp-release@sha256:039a4ef7c128a049ccf916a1d68ce93e8f5494b44d5a75df60c85e9e7191dacc
4.4.4 quay.io/openshift-release-dev/ocp-release@sha256:baa687f29b0ac155d8f4c6914056d36d68f343feb9c1e82b46eef95819d00be5
```

content/en/docs/architecture/ci-operator: Document explicit release version

---

content/en/docs/architecture/branch-protection.md

/assign @petr-muller 
Is there any reason to keep mentioning `protect: false`? I kept the table because it's useful, but I think it might be nice to otherwise hide the setting, as its so confusing?

Branchprotection: Document unmanaged: true

---

content/en/docs/how-tos/adding-a-new-secret-to-ci.md

Mention that the Vault self-service will need a user to log in before they're listed as potential members in "Edit Members".

adding-a-new-secret-to-ci: Users must log in

---

content/en/docs/how-tos/onboarding-a-new-component.md

We use github apps now so this isn't needed anymore.

Onboarding: Remove superfluous webhook set up

---

content/en/docs/how-tos/add-jobs-to-testgrid.md

So folks searching for `broken` are more likely to be able to realize that's how you mark a job broken.

content/en/docs/how-tos/add-jobs-to-testgrid: Mention 'broken' near _allow-list.yaml

---

content/en/docs/how-tos/contributing-openshift-release.md

https://github.com/openshift/ci-tools/pull/2070 updated ci-operator to allow `skip_if_only_changed` in jobs, in a fashion similar to `run_if_changed`. Add it to the documentation.

Document `skip_if_only_changed`

---

config.yaml

/hold
we should verify if it works on the preview of this PR after https://github.com/openshift/release/pull/19507 is merged.
/cc @alvaroaleman

Fix the cluster-display's URL

---

content/en/docs/architecture/ci-operator.md

Attempting to cut over from `cluster_pool`+`ipi-aws` to `cluster_claim`, it took several false starts, experimentation, and pawing through docs to figure out that `generic-claim` was the missing piece. Beef up the docs to help future users.

Advertise `generic-claim` workflow for `cluster_claim`

---

content/en/docs/architecture/ci-operator.md

Document the validation that will be fully enforced with
https://github.com/openshift/ci-tools/pull/2062.
This PR does not depend on the one above as this has always been an
implicit rule, it just was not properly validated.

ci-operator: document pipeline namespace conflicts

---

content/en/docs/how-tos/cluster-claim.md

The previous document assumed too much knowledge about everything: Hive, OCP installer, OpenShift CI custom secret management... We gave the user links and let him connect the pieces together. I attempted to write a much more detailed doc a user can directly follow, with links being used only to provide necessary background if needed.
/cc @stevekuznetsov @hongkailiu 
/cc @jsztuka 
Please take a look if a doc like this would improve your experience with setting up the custom pool, thanks!

Improve cluster pool creating document

---

content/en/docs/how-tos/testing-operator-sdk-operators.md

The step was renamed in https://github.com/openshift/release/pull/19702.

how-tos: correct link to `subscribe` step

---

content/en/docs/how-tos/contributing-openshift-release.md

Update docs to reflect https://github.com/openshift/ci-tools/pull/2199

Update feature branch description

---

content/en/docs/how-tos/testing-operator-sdk-operators.md

Clarify `context_dir/dockerfile_path` descriptions

---

content/en/docs/how-tos/adding-a-cluster-profile.md

The cluster profiles are in `ci` namespace, so the instructions to inject custom secrets into cluster profiles should not mention the `test-credentials` one.

Fix docs for injecting user-owner secrets to cluster profiles

---

content/en/docs/architecture/branching.md

Clarify that the `promotion` stanza needs to go in the config for your default branch (e.g. [here][1]), so folks don't think they need an entry in each release branch (although [that's ok too][2], it just doesn't affect future automated branching).
[1]: https://github.com/openshift/release/blob/a1cc80a690ae938516f239d4fd440ae777741207/ci-operator/config/openshift/kubernetes/openshift-kubernetes-master.yaml#L81
[2]: https://github.com/openshift/release/blob/a1cc80a690ae938516f239d4fd440ae777741207/ci-operator/config/openshift/kubernetes/openshift-kubernetes-release-4.9.yaml#L81

content/en/docs/architecture/branching: Automated branching via default branch config

---

content/en/docs/architecture/timeouts.md

Because `default_decoration_configs` is per org, or per org/repo.  With this commit, the syntax for per-job timeout bumps will be more discoverable.

content/en/docs/architecture/timeouts: Document raising the ProwJob timeout for specific jobs

---

OWNERS

This change will avoid selecting Steve, Alvaro and Alex from being assigned to PRs.

Set DPTP as exclusive reviewers

---

content/en/docs/architecture/timeouts.md

Catching up with openshift/ci-tools@2294, CC @vrutkovs, @petr-muller.

content/en/docs/architecture/timeouts: Document config test 'timeout'

---

content/en/docs/how-tos/onboarding-a-new-component.md

The docs for how to configure Tide in the releases repo were out of
date, which made it somewhat confusing to readers. Update them to
reflect what you actually have to do to configure Tide on a new repo.

Onboarding: Improve Tide configuration instructions

---

content/en/docs/getting-started/examples.md

There's no need to promote images that have no known consumer; it just clutters up the target namespace.
And if folks accidentally promote images that ask to be included in OpenShift releases, it can lead to redundant manifests and impact OKD releases, openshift/release#23351.

content/en/docs/getting-started/examples: Qualify promotion advice

---

content/en/docs/architecture/timeouts.md

I guess I'd been conflicted about inline vs. reference-style links in 52d2e13f91 (#196).  Consolidate around reference-style links for this external URI.

content/en/docs/architecture/timeouts: Fix generated-timeout-example ref

---

content/en/docs/architecture/ci-operator.md

Update the markdown in ci-operator.md and fix the markdown list item syntax for the individual pre-submit fields being listed so they properly render as list items.
See the previous rendering:

Update the list ordering for pre-submit fields in ci-operator.md

---

content/en/docs/architecture/ci-operator.md

Follow up https://coreos.slack.com/archives/CBN38N3MW/p1637962019020900?thread_ts=1637953164.013100&cid=CBN38N3MW
`ci-operator` clones the repo to `/go`.
https://github.com/openshift/ci-tools/blob/ef234d3d3c0ae6d26f2d25469b684a8602f691bb/pkg/steps/source.go#L198
That is what we do for ci-tools' boot_image:
https://github.com/openshift/release/blob/1c866e5a7f242d5c8d71627a943525be38fbc4c1/clusters/app.ci/supplemental-ci-images/ci-tools-build-root.yaml#L79

Document writable /go for build_root

---

content/en/docs/how-tos/onboarding-a-new-component.md

This extra info will help our users understand how long they may have to wait for auto-accept, and also provide our team with the specific job names to run if someone requests it happen immediately.

add info about specific bot invitation accepting jobs

---

content/en/docs/release-oversight/payload-testing.md

/hold
Require https://github.com/openshift/ci-tools/pull/2583

Refuse /payload command on PRs to repositories not contributing to OCP

---

layouts/partials/head.html

With the PR, the details shows up as expected:
It looks like some variable conflicting (without the PR).
Tried to rename some variables but the problem stays.
Moving the function into its own `$(document).ready()` fixes it.

Fix table_pools' row details

---

content/en/docs/how-tos/mirroring-to-quay.md

Vault secrets do not accept "dots" in the value field. Update the documentation with a correct example.

Fix typo in Vault secrets format

---

content/en/docs/how-tos/adding-a-cluster-profile.md
content/en/docs/how-tos/onboarding-a-new-component.md

Based on recent changes in `ci-tools` which tried to make this process as
simple as possible.  This area has been kept intentionally obscure but,
with no immediate plan for deprecation, there's no reason to make users
(and `dptp-helpdesk`, by extension) suffer.
/hold
To be merged after all `ci-tools` changes.

how-tos: add more cluster profile instructions

---

content/en/docs/architecture/step-registry.md
content/en/docs/getting-started/useful-links.md

There's already a link in the header/menu via config.yaml, but while hunting for this service in docs recently I realized that I apparently skim by the header without actually reading it.  Put some more links in likely places as a backstop for other folks also skimming past the header.
While I'm touching things, also update to sippy.dptools to catch up with openshift/release#28039.

content/en/docs: Services and step-docs links to steps.ci

---

content/en/docs/architecture/ci-operator-internals/_index.md

So folks know how long they need to wait before kicking off a retest if they want to pick up a fresh namespace with new release-image content.  As an alternative to inlining the values here, we could expose them in CI-operator logging, and then tell folks which log lines to look for, or some such.  As long as the process is less mysterious.

content/en/docs/architecture/ci-operator-internals: List namespace timeouts

---

content/en/docs/how-tos/artifacts.md

Missed previously due to the extreme noise in the `links` job.
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ci-docs/233/pull-ci-openshift-ci-docs-master-links/1554064037258465280#1:build-log.txt%3A24-25

artifacts: fix link

---

content/en/docs/getting-started/useful-links.md

Catching up with openshift/release@82aa961a82 (openshift/release#18760).

content/en/docs/getting-started/useful-links: Link arm64 release controller

---

content/en/docs/architecture/ci-operator.md

Documents https://github.com/openshift/ci-tools/pull/2932
Useful for https://issues.redhat.com/browse/KCP-198
/assign @droslean

ci-operator: document publishing by commit hash

---

content/en/docs/how-tos/external-images.md

People occasionally try to mirror an image from `docker.io` and we always have issues with it. Most recent problem: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-image-mirroring-supplemental-ci-images/1559555641926750208

Add a warning about mirroring from docker.io

---

content/en/docs/how-tos/rbac.md

I have had a couple of people ask about why they still don't have permissions right after updating the config. We should warn people that it can take up to `24h`.

Add info about time required to sync rover groups

---

content/en/docs/architecture/ci-operator-internals/observer-pods.md

The user facing documentation that comprises:
- a short introduction describing why observer exist
- how to define an observer
- how the execution model works
- some features, in order to highlight differences with regular tests
/cc @jmguzik @smg247
@smg247 I'm including you too just for a quick revision on english grammar, if you have time.

Observer pods: docs

---

content/en/docs/architecture/ci-operator-internals/observer-pods.md

It seems unlikely that observers would do something in the presence of kubeconfig, but be fine skipping that thing in its absence.  Pivot the example to a poll loop that will wait until a kubeconfig is available.  Personally I'd like gathered step logs to use `--timestamps`, but in the absence of that, I'm manually including timestamps in my output lines to make it easier to tell when the kubeconfig shows up.
Follows up on #287, CC @danilo-gemoli

content/en/docs/architecture/ci-operator-internals/observer-pods: Wait-for-KUBECONFIG

---

content/en/docs/how-tos/onboarding-a-new-component.md

We had a question about adding the `io.openshift.release.operator` for ART builds, would like to clarify that this is for the image owner to do in the right order in this process.

onboarding-a-new-component.md: clarify process for 2nd-level addition

---

content/en/docs/how-tos/pr-reminder.md

For https://issues.redhat.com/browse/DPTP-3053
I also added more info about how PRs are selected as I have been asked that question recently

`pr-reminder`: add info about the ability to configure private repos

---

content/en/docs/release-oversight/improving-ci-signal.md

The payload-testing docs landed in ece110f9ca (#213).  This commit adds a cross-link so folks wondering about CI signal/health have an easier time discovering /payload testing as a way to reduce TRT load and regression/reversion risk.

content/en/docs/release-oversight/improving-ci-signal: Link '/payload ...' doc

---

content/en/docs/how-tos/adding-a-cluster-profile.md

Document the process followed for the OpenVPN image in
https://github.com/openshift/release/pull/32777

how-tos: document image builds for VPN clients

---

content/en/docs/getting-started/useful-links.md

These are now stored in the DPTP "presentations" directory, which is accessible
by all of Red Hat (but not publicly).
---
People from outside the team request access to these with some frequency (e.g.
https://coreos.slack.com/archives/CBN38N3MW/p1663766854625619), and no one was
oppoosed to making them public.  This replaces private links with news ones
which are visible to all inside Red Hat.

useful-links: use public presentation links

---

content/en/docs/how-tos/contributing-openshift-release.md

Phase two beings today; the docs need to be updated to reflect that the label is now needed to merge a PR.
/cc @droslean @openshift/test-platform

`pj-rehearse` plugin: note that the 'rehearsals-ack' label is necessary for merge

---

content/en/docs/how-tos/interact-with-running-jobs.md

https://docs.ci.openshift.org/docs/getting-started/useful-links/#clusters
already describes the new authentication based on SSO, but the page describing
how to investigate test namespaces still describes the old GitHub-based method,
which is no longer available.

how-tos: update login instructions

---

content/en/docs/how-tos/contributing-openshift-release.md

self-explanatory.
/cc @droslean @openshift/test-platform

`pj-rehearse`: add information about the new 'reject' and 'refresh' commands

---

content/en/docs/how-tos/pr-reminder.md

We are moving the config in https://github.com/openshift/release/pull/33979, and should reference the new location in the docs.

`pr-reminder`: reference new config location

---

content/en/docs/architecture/ci-operator-internals/observer-pods.md

Added Timeout and GracePeriod to docs.
[release PR](https://github.com/openshift/release/pull/34338)
[ci-tools PR](https://github.com/openshift/ci-tools/pull/3161)
[DPTP-3184](https://issues.redhat.com/browse/DPTP-3184)
/cc @bbguimaraes

observer-pods: adding timeout and grace_period

---

content/en/docs/how-tos/onboarding-a-new-component.md

"What version am I building?" is something that many operators will care about.  Make it easy to figure out that information, by linking out from the central onboarding docs that component maintainers will pass through at some point, and hopefully return to (possibly after being linked back to these docs) when they want to revisit onboard-y sorts of issues.

content/en/docs/how-tos/onboarding-a-new-component: Mention Doozer environment variables

---

content/en/docs/how-tos/notification.md

Improve documentation on Slack alerts: how to deal with private channels.
I have found several errors from `crier` like the following:
`msg=failed to write Slack message, error=failed to post message to #kata-ocp-ci-reports: request failed: channel_not_found`
That's due the channel not being public, therefore ` @prow` is not able to post on it.
/cc @bbguimaraes

slack-alerts: note on private channels

---

content/en/docs/architecture/ci-operator.md

Catching up with openshift/ci-tools#2943

content/en/docs/architecture/ci-operator: Document prerelease 'stream' property

---

content/en/docs/how-tos/contributing-openshift-release.md

`pj-rehearse` updates: abort, re-trigger individual rehearsals, and warn about hidden

---

content/en/docs/how-tos/artifacts.md

These are periodically removed from GCS, so we cannot reference them here.
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ci-docs/319/pull-ci-openshift-ci-docs-master-links/1605215043228536832#1:build-log.txt%3A24

how-tos: remove link to artifacts

---

content/en/docs/how-tos/use-registries-in-build-farm.md

https://issues.redhat.com/browse/DPTP-3265
- `oc registry login --service-account` does not work any more.
- jsonpath of `kubectl` does not support logic and operator. Otherwise, we might not need `jq`.
- The `.dockercfg` file is not recognized by `podman 4.0.0` (I tested it). Otherwise, we might not need `oc registry login`.
[k8s doc](https://kubernetes.io/docs/concepts/configuration/secret/#docker-config-secrets) says 
"The kubernetes.io/dockercfg type is reserved to store a serialized ~/.dockercfg which is the legacy format for configuring Docker command line."
I am not sure why k8s/openshift still uses it to format the auth file since it is legacy and not recognized by `podman`.

Provide another way to get the registry authfile

---

content/en/docs/architecture/ci-operator-internals/configresolver.md
content/en/docs/architecture/ci-operator-internals/configuration-updates.md

ci-operator: document `ci-operator-configresolver`
---
ci-operator: document configuration updates
---
I know this is a huge documentation dump, but it's mostly a translation of my
notes from the investigation done in https://issues.redhat.com/browse/DPTP-2531
into a format more appropriate for https://docs.ci.openshift.org, which I think
would be a shame to leave in obscure Jira issues and Slack threads.
I've included most of the material for completeness, but we can decide whether
some parts need to be added or removed.  It's a single PR for now because the
documents are somewhat interdependent (they started as one but it got too big),
but it can be broken into smaller parts in future iterations.

ci-operator: document `ci-operator-configresolver`

---

content/en/docs/architecture/ci-operator-internals/artifacts.md
content/en/docs/architecture/ci-operator-internals/timeouts.md
content/en/docs/architecture/timeouts.md

https://deploy-preview-327--zealous-shirley-0f56b3.netlify.app/docs/architecture/ci-operator-internals/timeouts/
/hold
References:

ci-operator-internals: document timeouts

---

content/en/docs/architecture/ci-operator.md

openshift/ci-tools#3068 allows the `always_run` option to be configured in the CI config (not just in the Prow job).

Document setting always_run in CI configs

---

layouts/partials/head.html

Shows a message if there was an error while gathering info about a cluster (due to broken kubeconfig or anything else). The rest of the clusters are listed normally.
Back end changes were done in https://github.com/openshift/ci-tools/pull/3220.
for https://issues.redhat.com/browse/DPTP-3086
/cc smg247

useful-links: add cluster error message

---

content/en/docs/architecture/ci-operator.md

Follow up https://redhat-internal.slack.com/archives/CBN38N3MW/p1676646286837089
/cc @openshift/test-platform @asergienk 
Besides the tool, there are other things that we need to consider if we want remove the limitation, e.g., the pull secret to pull the images in the payload.

Cannot claim non-released clusters

---

Dockerfile.links

This reverts commit a8d562541295357cba2e166a8b52ac4cf6953b19.
Move the step to base image.
https://github.com/openshift/release/pull/36568/files

Revert "links image: install bash"

---

content/en/docs/internals/testing.md

Initial version of the documentation page describing how to test `ci-operator`.
Currently goes from zero to a basic test execution.  Based on my notes and the
recent team presentations.
I'm still making changes to our clusters and to `ci-operator` as I work on other
related things to make this process as simple as possible.  I still plan to
expand this document much further, but I'm opening it for early review.
https://deploy-preview-235--zealous-shirley-0f56b3.netlify.app/docs/architecture/ci-operator-internals/testing/

ci-operator-internals: add testing page

---

content/en/docs/architecture/jira.md

This PR adds a documentation for the jira-lifecycle-plugin's functionality, mostly based on the documentation for the bugzilla plugin.

content: add jira page

---

content/en/docs/how-tos/naming-your-ci-jobs.md

This adds guidelines for naming CI jobs based on how existing jobs are named. It's not intended to force anyone to rename older jobs (job renames have historically been quite disruptive to things like historical data collection), but rather provide guidance in how teams should name new CI jobs.

Add a "how to" for naming your CI job

---

content/en/docs/how-tos/adding-a-cluster-profile.md

The Reaper reads resource types from the same configuration file of Boskos, see [here](https://github.com/openshift/release/blob/6f16ca30d33ea8c700e1100e3e930a0dc1a5636c/clusters/app.ci/prow/03_deployment/boskos_reaper.yaml#L26), since [#36642](https://github.com/openshift/release/pull/36642) has been merged.
Documentation has to be updated accordingly.

Cluster Profile: "Adding New Leases" example PR needs no reaper anymore

---

content/en/docs/architecture/ci-operator.md

`stream` was moved within `version_bounds` in https://github.com/openshift/ci-tools/pull/3314

Reference the new `stream` location

---

content/en/docs/release-oversight/disruption-testing/data-architecture.md
content/en/docs/release-oversight/disruption-testing/job-primer.md

[TRT-853](https://issues.redhat.com//browse/TRT-853)
When I did work on TRT-826, I had to research this so I'm adding it to the docs on disruption.
This doc depends on the [create-tables CronJob](https://github.com/openshift/continuous-release-jobs/pull/1282) merging and becoming operational.

Mention the create-tables command and uploader jobs that depend on it

---

content/en/docs/how-tos/testing-operator-sdk-operators.md

Many thanks to @qbarrand 
He has made [a test](https://github.com/openshift/release/blob/278d44591ebc327c8e399102845fa321f9fca838/ci-operator/config/rh-ecosystem-edge/kernel-module-management/rh-ecosystem-edge-kernel-module-management-main.yaml#L109-L122) with `operator-sdk` using the bundle image built in CI.
This PR steals the test for an example in our doc.

oo-testing: doc an operator-sdk example

---

content/en/docs/release-oversight/disruption-testing/_index.md
content/en/docs/release-oversight/disruption-testing/aggregated-disruption.md
content/en/docs/release-oversight/disruption-testing/code-implementation.md
content/en/docs/release-oversight/disruption-testing/job-primer.md

[TRT-865](https://issues.redhat.com//browse/TRT-865)
Aggregation of disruption was re-activated on Jan 27, 2023 with this [PR](https://github.com/openshift/ci-tools/pull/3243/files) so we remove the banner that says otherwise.
Also, add a few notes on aggregated disruption regarding interpreting the results and some ways to modify it as needs dictate.

Updated doc to reflect disruption aggregation

---

content/en/docs/how-tos/contributing-openshift-release.md

Documents the changes from https://github.com/openshift/ci-tools/pull/3379
For: https://issues.redhat.com/browse/DPTP-3393

Document rehearsal changes from removing the manual refresh

---

content/en/docs/architecture/timeouts.md
content/en/docs/how-tos/cluster-claim.md

We shouldn't keep allowing anyone to use these. These really should only be used by the `openshift` org.
Also updated a dead link to the latest version.

Note restrictions on `openshift-ci` pools to `openshift` org

---

content/en/docs/how-tos/onboarding-a-new-component.md

I ran into this case today in this [thread](https://redhat-internal.slack.com/archives/CBN38N3MW/p1684776557539389). I believe that we didn't previously have this documented as we were using the gh app rather than the bot for `tide`.
Note: I also plan on updating `check-gh-automation` to verify the admin status.

note admin perms for openshift-merge-robot for tide

---

content/en/docs/architecture/release-gating.md

[TRT-1036](https://issues.redhat.com//browse/TRT-1036)
This documentation is quite old (still refers to build cop), this updates it to the latest guidelines from TRT for becoming a release informer or gating job.

Update release gating documentation

---

content/en/docs/how-tos/testing-operator-sdk-operators.md

This PR adds a section about using the Cluster Bot to test optional operator PRs.

operator-sdk-operators: include cluster bot docs

---

content/en/docs/architecture/quota-and-leases.md

Thanks to [kubernetes-sigs/boskos#157](https://github.com/kubernetes-sigs/boskos/pull/157) there is no need to keep the `reaper`'s config in sync with the `boskos`'s one anymore.
/cc @smg247

`boskos`: Reaper config update not needed anymore

---

content/en/docs/how-tos/contributing-openshift-release.md

https://issues.redhat.com/browse/DPTP-3477
We do not use those CMs any more.
https://github.com/openshift/release/pull/42202#issuecomment-1674481817

Remove doc about sharding

---

content/en/docs/getting-started/useful-links.md
layouts/partials/head.html

As shown with the above image, our fix should work when some cluster is not available.
However, at the recent outage, we still cannot see the whole section of cluster. This might be caused by `cluster-display` crashed. I did not get the chance to debug further during the outage.
With the PR, if I do not start `cluster-display` at all:
/cc @psalajova @smg247

Show status for ajax calls on clusters

---

content/en/docs/architecture/timeouts.md
content/en/docs/internals/observer-pods.md

After the update to [entrypoint](https://github.com/kubernetes/test-infra/pull/30169) and [entrypoint wrapper](https://github.com/openshift/ci-tools/pull/3561) the error code of the observers could be propagated ([ci-tools/#3560](https://github.com/openshift/ci-tools/pull/3560), [ci-tools/#3575](https://github.com/openshift/ci-tools/pull/3575)), but changes to the observer script need to be made to run properly (see [release/#43489](https://github.com/openshift/release/pull/43489) ) and the doc should be updated then.
/cc @bbguimaraes

`observers`: update on using trap

---

content/en/docs/getting-started/useful-links.md
content/en/docs/how-tos/interact-with-running-jobs.md

We will have more and more automation depending on the GitHub link in Rover People and thus we move the information to a more visible place.
https://issues.redhat.com/browse/DPTP-3328
/assign @Prucek

Emphasize GitHub link in Rover People

---

.gitignore
layouts/partials/head.html

- `node_modules/` is the folder generated on the dev env to store the dependencies. They should not be pushed to Git repo.
- It already caused issues with higher version of Hugo or NodeJS. Let us see if we can remove it even in the lower version.

Clean up the repo

---

content/en/docs/how-tos/onboarding-a-new-component.md

Supplement "sync with ART" with some steps that all OpenShift admins can use to self-serve "yes, my image `$NAME` is in position for both ART and CI `$VERSION` ImageStreams".  Also provide an example of "I'm not quite sure what my image's name is in this ImageStream..." lookup.  ~And link the ART dashboard so folks can look for builds to see if their image is failing to build.~ [edit: [I'm no longer linking the ART dashboard][1]]
Also an unrelated change to pick the pretty URI for the amd64 release controller.
[1]: https://github.com/openshift/ci-docs/pull/399#issuecomment-1788146571

content/en/docs/how-tos/onboarding-a-new-component: Self-checks for image presence

---

layouts/partials/head.html

This PR corrects the description for `multi01` and `vsphere2`.
/assign @bear-redhat

Fix cluster's description

---

content/en/docs/how-tos/contributing-openshift-release.md

One of the tasks from build01's outage.
1. ProwGen does not  change the filed but it is managed by other ci-tools.
2. Discourage to use the `cluster` field unless you know what you are doing.

Clarify the usage of the cluster field

---

content/en/docs/architecture/timeouts.md

For folks that cargo-cult these blocks, the `exit 1` will cause their tests to perma-fail. Don't ask me how I know.

timeouts.md: remove exits

---

content/en/docs/architecture/branching.md
content/en/docs/architecture/ci-operator.md
content/en/docs/getting-started/examples.md
content/en/docs/how-tos/use-registries-in-build-farm.md

Adjust the documentation in accordance with https://github.com/openshift/ci-tools/pull/3858
Existing reference to:
```yaml
promotion:
...
```
have updated to:
```yaml
promotion:
to:
...
```
Add new section that describes how to promote to multiple target.

promotion: support multiple targets

---

content/en/docs/how-tos/adding-a-cluster-profile.md

Creating a separate profile for AWS resources requires AWS credentials, which need to be stored as a secret in Vault. This commit elaborates on what the `ipi-aws` workflow requires to provision resources in AWS.

Update cluster profile docs with AWS credential details

---

content/en/docs/release-oversight/payload-testing.md

The restriction that the PRs be from distinct repositories is no longer necessary
For: https://issues.redhat.com/browse/DPTP-3691

Allow for payload testing with multiple PRs from the same repository

---

netlify.toml

/cc nobody
Let us see if it fix the build.
I can build it locally with
```console
$ hugo version
hugo v0.119.0-b84644c008e0dc2c4b67bd69cccf87a41a03937e+extended darwin/arm64 BuildDate=2023-09-24T15:20:17Z VendorInfo=brew
$ node -v
v20.11.1
```

Fix the netlify build

---

content/en/docs/how-tos/external-images.md

/hold
Need more soaking time for the existing changes such as importing from QCI, and mirroring the supplemental CI images.

Document the new way of using external images in CI

---

content/en/docs/architecture/private-repositories.md
content/en/docs/how-tos/onboarding-a-new-component.md
content/en/docs/internals/artifacts.md
content/en/docs/internals/configuration-updates.md
content/en/docs/internals/steps.md
content/en/docs/internals/timeouts.md

This updates url references for prow repository. https://github.com/kubernetes-sigs/prow
Fixing failures observed in https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_ci-docs/445/pull-ci-openshift-ci-docs-master-links/1780324439380987904 

Update links for prow repository

---

content/en/docs/internals/_index.md

IMO the line below the deleted one says the exact same thing, so I suggest deleting this one.

`image pipeline`: remove duplicit entry

---

layouts/partials/head.html

Replaces links (strings starting with http://, https://, or www) with HTML link tags. Builds upon https://github.com/openshift/ci-docs/pull/462
/cc @smg247

Make links in text clickable

---

content/en/docs/how-tos/use-registries-in-build-farm.md

It might be still not clear enough why the ART images are still on app.ci instead of QCI.
Here is the slack discussion (which i think might be helpful)
https://issues.redhat.com/browse/DPTP-3959?focusedId=24654668&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-24654668
/cc @deepsm007 @smg247

Clarify why the ART images are still on app.ci

---

content/en/docs/internals/images-in-ci.md

qci doc: add links to QCI's manifests

---

layouts/partials/head.html

We recently had an FAQ item added with a link in the `subject`. We can display it nicely as well. There will never be links in the `topic` so that is left unchanged.

`helpdesk-faq`: `Subject` links also need to be formatted

---

content/en/docs/architecture/jira.md

b4c09f89b3 (#457) landed docs for comma delimiters, but[ the Prow implementation says][1]:
> If multiple branches are specified, separated by a space...
and [uses `strings.Fields`][2], [which splits on whitespace][3].
[1]: https://github.com/kubernetes-sigs/prow/pull/136/files#diff-af91169cc704bac88f2d69a646fb521532a06add42cf44f1d9a5e7c4007e3f78R76
[2]: https://github.com/kubernetes-sigs/prow/pull/136/files#diff-af91169cc704bac88f2d69a646fb521532a06add42cf44f1d9a5e7c4007e3f78R192
[3]: https://pkg.go.dev/strings#Fields

content/en/docs/architecture/jira: Comma -> space, when /cherrypick'ing multiple branches

---

content/en/docs/how-tos/naming-your-ci-jobs.md

The multiarch team has defined a pattern to follow for naming ci jobs that utilize the multi-payload.  This PR links the different places of documentation to one another.

MULTIARCH-4359 Adding documentation for multiarch payload job names

---

content/en/docs/release-oversight/pull-request-testing.md

I am in the process of creating validation for this warning, and realized that the "payload-aggregate" command shouldn't have this limitation.

multiple "payload-aggregate" commands in a single comment are supported

---

content/en/docs/architecture/branching.md

-  Removing references to Bugzilla
-  Removing references to code freeze
-  Briefly mentioned /acknowledge-critical-fixes-only
-  Moved the legacy-no-feature freeze docs to the FAQ

updates to our branching docs

---

content/en/docs/how-tos/onboarding-a-new-component.md

This has existed for a long time, but the onboarding doc contradicted the other page. Now we can link to that page.

Note that private repos are now supported

---

content/en/docs/internals/dynamic-scheduling.md

This PR remove the `grep` and "copy/paste" steps since we can directly specify the deployment name.

Simplified "oc exec" when re-triggering dispatcher

---

content/en/docs/how-tos/multi-architecture.md

Title is not needed since the documentation page is adding the Description from the metadata.

remove unnessacary title in the multi arch documentation

---

content/en/docs/architecture/quota-and-leases.md

take out the [grafana dashboard ](https://grafana-route-ci-grafana.apps.ci.l2s4.p1.openshiftapps.com/d/628a36ebd9ef30d67e28576a5d5201fd/boskos-dashboard?orgId=1)reference until the serivce is restored or an new one constructed via Prometheus.

remove section of the doc that reference granfana dashboard

---

content/en/docs/how-tos/cluster-claim.md

Make it clearer that the namespaces must match. 
Prompted by this slack thread: https://redhat-internal.slack.com/archives/CBN38N3MW/p1748533561055599 where a cluster pool was failing to initialize because it couldn't find the secret with credentials, because the secret was in a different namespace.

Harmonize namespace names

---

content/en/docs/architecture/jira.md

Add documentation for new `/verified by` and `/verified later` commands for the jira-lifecycle-plugin.
This PR also removes documentation for an older premerge verification method that was added for QE. This method ended up being unused, so the documentation has been removed to avoid confusion with the new premerge verification method.

jira: update premerge verification documentation

---

content/en/docs/how-tos/triggering-prowjobs-via-rest.md

After: https://github.com/openshift/ci-tools/pull/4498, it is possible to set environment variable overrides directly from gangway, for variables that start with the prefix `MULTISTAGE_PARAM_OVERRIDE_`.

gangway: add environment variable override documentation
